name: Go
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Test and lint
        env:
          GOLANGCI_LINT_VERSION: "v1.19.1"
        run: |
          echo "Installing golangci-lint version ${GOLANGCI_LINT_VERSION}"
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s "${GOLANGCI_LINT_VERSION}"
          export PATH="${PATH}:$(pwd)/bin"

          echo "Installing latest golint"
          GO111MODULE=off go get -u golang.org/x/lint/golint
          export PATH="${PATH}:${GOPATH}/bin:/home/runner/go/bin/"

          go test ./...

          golint ./...

          golangci-lint
